version: '3.8'

services:
  vmtea:
    build: .
    container_name: vmtea
    volumes:
      - .:/app
      - ./privatekey.txt:/app/privatekey.txt
      - ./toaddress.txt:/app/toaddress.txt
      - ./config.json:/app/config.json
      - ./node_modules:/app/node_modules
    working_dir: /app
    command: npm start
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  scheduler:
    image: alpine:latest
    container_name: vmtea_scheduler
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: >
      sh -c "apk add --no-cache docker-cli &&
             echo '0 */8 * * * docker restart vmtea' | crontab - &&
             crond -f"
